beagle/ide/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.views.generic.simple import redirect_to

urlpatterns = patterns('ide.views',
  url('^filetree/$', 'filetree', name='ide-filetree'),
  url('^dirchooser/$', 'dirchooser', name='ide-dirchooser'),
  url('^fileget/$', 'fileget', name='ide-fileget'),
  url('^filesave/$', 'filesave', name='ide-filesave'),
  url('^accounts/login/$', 'login', name='ide-login'),
  url('^favicon.ico$', redirect_to, {'url': settings.STATIC_URL + 'ide/img/favicon.ico'}, name='ide-favicon.ico'),
  url('^new/$', 'new', name='ide-new'),
  url('^delete/$', 'remove', name='ide-delete'),
  url('^copy/$', 'copy', name='ide-copy'),
  url('^paste/$', 'paste', name='ide-paste'),
  url('^rename/$', 'rename', name='ide-rename'),
  url('^temp_file/$', 'temp_file', name='ide-temp-file'),
  url('^view_file(?P<fp>.+)$', 'view_file', name='ide-view-file'),
  url('^external_open(?P<fp>.+)$', 'external_open', name='ide-ext-open'),
  url('^save_image(?P<fp>.+)$', 'save_image', name='ide-save-image'),
  url('^external_request/(?P<key>.+)/fp(?P<fp>.+)$', 'external_request', name='ide-ext-req'),
  url('^save_session/$', 'save_session', name='ide-save-session'),
  
  url('^editor_pref/$', 'editor_pref', name='ide-editor-pref'),
  url('^term_pref/$', 'term_pref', name='ide-terminal-pref'),
  
  url('^terminal/$', 'terminal', name='ide-terminal'),
  
  url('^$', 'home', name='ide-home'),
)

beagle/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
  url(r'^admin/', include(admin.site.urls)),
  url(r'', include('beagle.ide.urls')),
)

if settings.DJANGO_SERVE_STATIC_MEDIA:
  urlpatterns += patterns('',
    url(r'^%s(?P<path>.*)$' % settings.STATIC_URL[1:-1], 'django.views.static.serve',  {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
  )
  
if settings.DJANGO_SERVE_STATIC_MEDIA or settings.DEBUG:
  urlpatterns += patterns('',
    url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:-1], 'django.views.static.serve',  {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
  )
  

beagle/ide/models.py
import os
import time

from django.db import models
from django.contrib.auth.models import User
import django.utils.simplejson as json

TEMA_ARAYUZ = (
    ('default', 'Default'),
    ('black', 'Black'),
    ('blueopal', 'Blue Opal'),
    ('metro', 'Metro'),
    ('silver', 'Silver')
)

TEMA_EDITOR = (
    ('textmate', 'TextMate'),
    ('eclipse', 'Eclipse'),
    ('dawn', 'Dawn'),
    ('idle_fingers', 'idleFingers'),
    ('pastel_on_dark', 'Pastel on dark'),
    ('twilight', 'Twilight'),
    ('clouds', 'Clouds'),
    ('clouds_midnight', 'Clouds Midnight'),
    ('crimson_editor', 'Crimson'),
    ('kr_theme', 'krTheme'),
    ('mono_industrial', 'Mono Industrial'),
    ('monokai', 'Monokai'),
    ('merbivore', 'Merbivore'),
    ('merbivore_soft', 'Merbivore Soft'),
    ('vibrant_ink', 'Vibrant Ink'),
    ('solarized_dark', 'Solarized Dark'),
    ('solarized_light', 'Solarized Light'),
)

BOYUT = (
    ('6px', '6px'),
    ('7px', '7px'),
    ('8px', '8px'),
    ('9px', '9px'),
    ('10px', '10px'),
    ('11px', '11px'),
    ('12px', '12px'),
    ('13px', '13px'),
    ('14px', '14px'),
    ('15px', '15px'),
    ('16px', '16px'),
    ('17px', '17px'),
    ('18px', '18px'),
    ('19px', '19px'),
    ('20px', '20px'),
    ('21px', '21px'),
    ('22px', '22px'),
    ('23px', '23px'),
    ('24px', '24px'),
)

TUSLAR = (
    ('ace', 'Ace'),
    ('vim', 'Vim'),
    ('emacs', 'Emacs')
)

WRAP = (
    ('off', 'Off'),
    ('40', '40 Chars'),
    ('80', '80 Chars'),
    ('free', 'Free')
)
  
class Preferences (models.Model):

    user = models.OneToOneField(User)

    idename = models.CharField('IDE Adi', max_length=255, default="Beagleboard IDE")
    basedir = models.CharField('Ana Dizin', max_length=255)
    uitheme = models.CharField('Arayuz Temasi', choices=TEMA_ARAYUZ, max_length=25, default='silver')
    theme = models.CharField('Editor Temasi', choices=TEMA_EDITOR, max_length=25, default='textmate')
    fontsize = models.CharField('Font Boyutu', choices=BOYUT, max_length=10, default='14px')
    keybind = models.CharField('Tus Secimi', choices=TUSLAR, max_length=10, default='ace')
    swrap = models.CharField('Satir Wrap', choices=WRAP, max_length=10, default='off')

    tabsize = models.IntegerField('Tab Boyutu', default=4)

    hactive = models.BooleanField('Aktif Satiri Belirt', default=True)
    hword = models.BooleanField('Aktif Kelimeyi Belirt', default=True)
    invisibles = models.BooleanField('Gizli Dosyalari Goster', default=False)
    gutter = models.BooleanField('Show Gutter', default=True)
    pmargin = models.BooleanField('Yazilabilir Alani Goster', default=True)
    softab = models.BooleanField('Hafif Tab Kullan', default=True)
    behave = models.BooleanField('Davranislar', default=True)
    splitterm = models.BooleanField('Split Terminal/IDE Ayiraci', default=True)
    save_session = models.BooleanField('Save Session', default=True)

    session = models.TextField(blank=True, null=True)

    bg = models.ImageField('Terminal Arkaplani', blank=True, null=True, upload_to='bg')

    font = models.CharField('Terminal Fontu', max_length=255, default='"Courier New", Courier, "Lucida Sans Typewriter", "Lucida Typewriter", monospace')
    tfontsize = models.CharField('Terminal Font Boyutu', max_length=25, default='16px')

    def last_session (self):
        if self.session:
            return json.dumps(self.session.split("\n"))
        return '[]';
    
    def valid_path (self, path):
        path = os.path.normpath(path)
        if path.startswith(self.basedir):
            return True
      
        return False

class TempFile (models.Model):
    user = models.ForeignKey(User)
    file = models.FileField(upload_to='tmp')
  
class ExtFileRequest (models.Model):
    secret = models.CharField(max_length=255)
    path = models.TextField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)

beagle/ide/forms.py
from django import forms

import ide.models

class EditorPref (forms.ModelForm):
    class Meta:
        model = ide.models.Preferences
        exclude = ('user', 'basedir', 'session', 'bg', 'font', 'tfontsize')
    
class TermPref (forms.ModelForm):
    class Meta:
        model = ide.models.Preferences
        exclude = ('user', 'basedir', 'session', 'uitheme', 'theme', 'fontsize', \
                   'keybind', 'swrap', 'tabsize', 'hactive', 'hword', 'invisibles', \
                   'gutter', 'pmargin', 'softab', 'behave', 'save_session', 'splitterm')

beagle/ide/views.py
import os
import time
import shutil
import codecs
import urllib
import datetime
import traceback

from django import http
from django.conf import settings
from django.template.response import TemplateResponse
import django.utils.simplejson as json
from django.contrib.auth.decorators import login_required
import django.contrib.auth.views as auth_views
from django.template.loader import render_to_string
from django.core.files.uploadedfile import SimpleUploadedFile
from django.views.static import serve
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt

import ide.utils
import ide.settings
import ide.models
import ide.forms
from ide.templatetags.ntags import hashstr

GOOD_CSTATES = ("SUCCESS", "STARTED", "RECEIVED")
CLIPBOARD = ""

def login (request):
  return auth_views.login(request)
  
@login_required
def home (request):
  try:
    base_dir = request.user.preferences.basedir
    idename = request.user.preferences.idename
  except:
    return TemplateResponse(request, 'ide/message.html', {'message': 'Admin ayarlarini buradan doldurunuz.'})
  
  c = {
    'MODES': ide.settings.MODES,
    'THEMES': ide.settings.THEMES,
    'idename': idename,
    'dir': base_dir,
    'did': 'file_browser',
    'd': base_dir,
    'TERMINAL_ON': ide.settings.TERMINAL_ON
  }

  return TemplateResponse(request, 'ide/home.html', c)
  
@login_required
def temp_file (request):
  fn = request.GET.get('name')
  
  mt = ide.utils.mimetype(fn)
  f = SimpleUploadedFile(fn, request.raw_post_data, mt)
  
  t = ide.models.TempFile(file=f, user=request.user)
  t.save()
  
  return ide.utils.good_json(t.id)
  
@login_required
@ide.utils.valid_dir
def new (request):
  d = request.REQUEST.get('dir', '')
  new_type = request.REQUEST.get('new_type', '')
  name = request.REQUEST.get('name', '')
  
  fp = os.path.join(d, name)
  
  if new_type == 'file':
    if os.path.exists(fp):
      return ide.utils.bad_json('File Exists Already')
      
    fh = open(fp, 'w')
    fh.close()
    
  elif new_type == 'dir':
    if os.path.exists(fp):
      return ide.utils.bad_json('Directory Exists Already')
      
    os.mkdir(fp)
    
  elif new_type == 'url':
    uh = urllib.urlopen(name)
    
    if uh.info().has_key('Content-Disposition'):
      if 'filename' in uh.info()['Content-Disposition']:
        fn = uh.info()['Content-Disposition'].split('filename=')[1]
        
      else:
        fn = uh.info()['Content-Disposition']
        
      if fn[0] == '"' or fn[0] == "'":
        fn = fn[1:-1]
        
    else:
      fn = name.split('/')[-1]
      if fn == '':
        fn = time.strftime("%Y%m%d_%H%M%S.file", time.gmtime())
        
    fp = os.path.join(d, fn)
    if os.path.exists(fp):
      return ide.utils.bad_json('File Exists Already')
      
    fh = open(fp, 'wb')
    while 1:
      data = uh.read()
      fh.write(data)
      
      if not data:
        break
        
    fh.close()
    uh.close()
    
  else:
    tf = request.REQUEST.get('temp_file')
    tf = ide.models.TempFile.objects.get(id=tf, user=request.user)
    
    name = os.path.basename(tf.file.path)
    
    fp = os.path.join(d, name)
    if os.path.exists(fp):
      tf.file.delete()
      tf.delete()
      return ide.utils.bad_json('File Exists Already')
      
    shutil.move(tf.file.path, fp)
    tf.delete()
    
  return ide.utils.good_json()
  
@login_required
def filesave (request):
  ret = 'bad'
  error = None
  
  path = request.POST.get('path', '')
  contents = request.POST.get('contents', '')
    
  if path == '':
    error = 'Bad Request'
    
  else:
    if request.user.preferences.valid_path(path):
      try:
        fh = codecs.open(path, encoding='utf-8', mode='w')
        fh.write(contents)
        
      except:
        error = 'Error writing file to disk.'
        
      else:
        fh.close()
        ret = 'good'
        
    else:
      error = 'File Access Denied'
      
  return http.HttpResponse(json.dumps({'result': ret, 'error': error, 'uid': hashstr(path)}), mimetype=settings.JSON_MIME)
    
@login_required
def fileget (request):
  try:
    base_dir = request.user.preferences.basedir
    
    f = request.POST.get('f', '')
    f = os.path.normpath(f)
    if not f.startswith(base_dir):
      raise http.Http404
      
    fh = open(f, 'rb')
    mode = None
    
    if ide.utils.istext(fh.read(512)):
      fh.seek(0)
      
      root, ext = os.path.splitext(f)
      if ext[1:].lower() in ide.settings.TEXT_EXTENSIONS.keys():
        mode = ide.settings.TEXT_EXTENSIONS[ext[1:].lower()]
        
      ret = {
        'fileType': 'text',
        'data': fh.read(),
        'path': f,
        'filename': os.path.basename(f),
        'mode': mode,
        'uid': hashstr(f)
      }
      
    else:
      ret = {'fileType': 'binary', }
      
    return http.HttpResponse(json.dumps(ret), mimetype=settings.JSON_MIME)
    
  except:
    import traceback
    traceback.print_exc()
    
@login_required
def filetree (request):
  r = ['<ul class="jqueryFileTree" style="display: none;">']
  show_hidden = False
  base_dir = request.user.preferences.basedir
  
  try:
    r = ['<ul class="jqueryFileTree" style="display: none;">']
    d = urllib.unquote(request.POST.get('dir', ''))
    
    if not d.startswith(base_dir):
      d = os.path.join(base_dir, d)
      
    d = os.path.normpath(d)
    #if not d.startswith(base_dir):
    #  r.append('Invalid directory: %s' % str(d))
      
    fdlist = os.listdir(d)
    fdlist.sort()
    
    files = []
    dirs = []
    
    for f in fdlist:
      go = False
      if f.startswith('.'):
        if show_hidden:
          go = True
          
      else:
        go = True
        
      if go:
        ff = os.path.join(d,f)
        if os.path.isdir(ff):
          dirs.append((ff,f))
          
        else:
          e = os.path.splitext(f)[1][1:] # get .ext and remove dot
          files.append((e,ff,f))
          
    for d in dirs:
      did = hashstr(d[0])
      rm = render_to_string('ide/right_menu_dir.html', {'dir': d[0], 'did': did, 'd': os.path.basename(d[0])})
      r.append('<li class="directory collapsed" id="%s" title="%s">%s<a href="#" rel="%s/">%s</a></li>' % (did, d[0], rm, d[0], d[1]))
      
    for f in files:
      fid = hashstr(f[1])
      rm = render_to_string('ide/right_menu_file.html', {'f': f[2], 'fid': fid, 'file': f[1]})
      r.append('<li class="file ext_%s" id="%s">%s<a href="#" rel="%s">%s</a></li>' % (f[0], fid, rm, f[1], f[2]))
        
    r.append('</ul>')
    
  except Exception,e:
    r.append('Could not load directory: %s' % str(e))
    
  r.append('</ul>')
  return http.HttpResponse(''.join(r))
  
@login_required
def dirchooser (request):
  r = ['<ul class="jqueryFileTree" style="display: none;">']
  show_hidden = False
  base_dir = request.user.preferences.basedir
  
  try:
    r = ['<ul class="jqueryFileTree" style="display: none;">']
    d = urllib.unquote(request.POST.get('dir', ''))
    
    if not d.startswith(base_dir):
      d = os.path.join(base_dir, d)
      
    d = os.path.normpath(d)
    if not d.startswith(base_dir):
      r.append('Invalid directory: %s' % str(d))
      
    fdlist = os.listdir(d)
    fdlist.sort()
    
    files = []
    dirs = []
    
    for f in fdlist:
      go = False
      if f.startswith('.'):
        if show_hidden:
          go = True
          
      else:
        go = True
        
      if go:
        ff = os.path.join(d,f)
        if os.path.isdir(ff):
          dirs.append((ff,f))
          
        else:
          e = os.path.splitext(f)[1][1:] # get .ext and remove dot
          files.append((e,ff,f))
          
    for d in dirs:
      short = urllib.quote(d[0].replace(base_dir + '/', ''))
      r.append('<li class="directory collapsed" title="%s"><a href="#" rel="%s/" onclick="choose_me(\'%s\')">%s</a></li>' % (d[0], d[0], short, d[1]))
      
    r.append('</ul>')
    
  except Exception,e:
    r.append('Could not load directory: %s' % str(e))
    
  r.append('</ul>')
  return http.HttpResponse(''.join(r))

  
@login_required
def view_file (request, fp=None):
  if ide.utils.valid_path(request, fp):
    fn = os.path.basename(fp)
    ret = serve(request, fp, document_root="/")
    ret['Content-Disposition'] = 'filename=%s' % fn
    return ret
    
  raise http.Http404
  
@login_required
def external_open (request, fp=None):
  if ide.utils.valid_path(request, fp):
    return ide.utils.external_service(request, fp)
    
  raise http.Http404
  
@csrf_exempt
@login_required
def save_image (request, fp=None):
  if ide.utils.valid_path(request, fp):
    fw = open(fp, 'wb')
    url = request.REQUEST.get(ide.settings.IMG_EDITOR_READ)
    fr = urllib.urlopen(url)
    fw.write(fr.read())
    fw.close()
    fr.close()
    
    return TemplateResponse(request, 'ide/close.html', {})
    
  raise http.Http404
  
def external_request (request, key=None, fp=None):
  efr = get_object_or_404(ide.models.ExtFileRequest, secret=key, path=fp)
  if settings.DEBUG:
    old = datetime.datetime.now() - datetime.timedelta(seconds=300)
    
  else:
    old = datetime.datetime.now() - datetime.timedelta(seconds=30)
    
  if efr.created > old:
    ret = serve(request, fp, document_root="/")
    
    return ret
    
  if not setting.DEBUG:
    efr.delete()
    
  raise http.Http404
  
@login_required
@ide.utils.valid_dir
def remove (request):
  path = request.REQUEST.get('dir')
  if os.path.isdir(path):
    shutil.rmtree(path)
    
  else:
    os.remove(path)
  
  d = os.path.dirname(path)
  if d == request.user.preferences.basedir:
    did = 'file_browser'
    
  else:
    did = hashstr(d)
    
  return ide.utils.good_json(did)

@login_required
@ide.utils.valid_dir
def copy (request):
  global CLIPBOARD
  path = request.REQUEST.get('dir')
  name = request.REQUEST.get('name')
  d = os.path.dirname(path)
  CLIPBOARD = os.path.join(d, name)

  if d == request.user.preferences.basedir:
    did = 'file_browser'
    
  else:

beagle/ide/templates/ide/close.html
<!DOCTYPE html>
<html> 
  <head>
    <meta charset="utf-8"/> 
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>So Long And Thanks For All The Fish</title>
  </head>
  <body>
    <h1>So Long And Thanks For All The Fish</h1>
    <script type="text/javascript">
      window.close();
    </script>
  </body>
</html>

beagle/ide/templates/ide/editor_pref.html
{% extends "ide/master_iframe.html" %}
{% block content %}
<form action="" method="post" class="pref_form">
  {% csrf_token %}
  <table>
    <tr>
      <td>
        {% if form.errors.uitheme %}{{ form.errors.uitheme }}{% endif %}
        Arayuz Temasi: {{ form.uitheme }}
      </td>
      <td>
        {% if form.errors.theme %}{{ form.errors.theme }}{% endif %}
        Editor Temasi: {{ form.theme }}
      </td>
    </tr>
    <tr>
      <td>
        {% if form.errors.keybind %}{{ form.errors.keybind }}{% endif %}
        Tus Secimi: {{ form.keybind }}
      </td>
      <td>
        {% if form.errors.swrap %}{{ form.errors.swrap }}{% endif %}
        Hafif Sarma: {{ form.swrap }}
      </td>
    </tr>
    <tr>
      <td>
        {% if form.errors.fontsize %}{{ form.errors.fontsize }}{% endif %}
        Font Boyutu: {{ form.fontsize }}
      </td>
      <td>
        {% if form.errors.tabsize %}{{ form.errors.tabsize }}{% endif %}
        Tab Boyutu: {{ form.tabsize }}
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <table>
          <tr>
            <td>
              {{ form.hactive }} <label for="id_hactive">Aktif Satiri Belirt</label>
            </td>
            <td>
              {{ form.hword }} <label for="id_hword">Aktif Kelimeyi Belirt</label>
            </td>
          </tr>
          <tr>
            <td>
              {{ form.invisibles }} <label for="id_invisibles">Gizli Dosyalari Goster</label>
            </td>
            <td>
              {{ form.gutter }} <label for="id_gutter">Show Gutter</label>
            </td>
          </tr>
          <tr>
            <td>
              {{ form.pmargin }} <label for="id_pmargin">Yazilabilir Alani Goster</label>
            </td>
            <td>
              {{ form.softab }} <label for="id_softab">Hafif Tab Kullan</label>
            </td>
          </tr>
          <tr>
            <td>
              {{ form.behave }} <label for="id_behave">Davranislar</label>
            </td>
            <td>{{ form.save_session }} <label for="id_save_session">Save Session</label></td>
          </tr>
          <tr>
            <td>
              {{ form.splitterm }} <label for="id_splitterm">Split Terminal/IDE Ayirici</label>
            </td>
            <td></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <input type="submit" name="task" value="Save"/>
      </td>
    </tr>
  </table>
</form>
{% endblock %}

beagle/ide/templates/ide/editor_pref_success.html
{% extends "ide/master_iframe.html" %}
{% block content %}
<h1 class="message">Ayarlandi :D</h1>
{% endblock %}
{% block footer %}
<script type="text/javascript">
  parent.update_prefs({{ new_prefs|safe }});
</script>
{% endblock %}

beagle/ide/templates/ide/master.html
<!DOCTYPE html>
<html> 
  <head>
	{% block mainhead %}
    <meta charset="utf-8"/> 
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}{{ idename }} &sdot; {{ request.get_host }}{% endblock %}</title>
    <link rel="shortcut icon" href="{{ STATIC_URL }}ide/img/favicon.ico" />
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700' rel='stylesheet' type='text/css'/>
    <link href='https://fonts.googleapis.com/css?family=Droid+Sans+Mono' rel='stylesheet' type='text/css'/>
    <link href='https://fonts.googleapis.com/css?family=Gentium+Basic' rel='stylesheet' type='text/css'>
    
    <link href='{{ STATIC_URL }}ide/js/jqueryFileTree/jqueryFileTree.css' rel='stylesheet' type='text/css'>
    <link href='{{ STATIC_URL }}ide/css/kendo_styles/kendo.common.min.css' rel='stylesheet' type='text/css'/>
    <link href='{{ STATIC_URL }}ide/css/beagle.css' rel='stylesheet' type='text/css'/>
    <link href='{{ STATIC_URL }}ide/css/kendo_styles/kendo.{{ request.user.preferences.uitheme }}.min.css' id="kendoStyle" rel='stylesheet' type='text/css'/>
    <link href='{{ STATIC_URL }}ide/css/buttons.css' rel='stylesheet' type='text/css'/>
    
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/jquery.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/jqueryFileTree/jqueryFileTree.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/jquery-ui/js/jquery-ui-1.8.13.custom.min.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/kendo.all.min.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/ace/build/src/ace.js'></script>
    {% for mode in MODES %}{% if mode.0 != 'text' %}<script src="{{ STATIC_URL }}ide/js/ace/build/src/mode-{{ mode.0 }}.js" type="text/javascript"></script>
    {% endif %}{% endfor %}
    {% for theme in TEMA_ARAYUZ %}{% if theme == request.user.preferences.theme %}<script src="{{ STATIC_URL }}ide/js/ace/build/src/theme-{{ theme }}.js" type="text/javascript"></script>{% endif %}{% endfor %}
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/ace/build/src/keybinding-emacs.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/ace/build/src/keybinding-vim.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/common.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/beagle.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/menu.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/modals.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/search.js'></script>
    {% endblock %}
    {% block head %}{% endblock %}
    {% if request.track %}{{ request.track_code|safe }}{% endif %}
  </head>
  <body>
    {% block content %}{% endblock %}
    {% block footer %}{% endblock %}
    <div style="display: none;">
      {% include "ide/modals.html" %}
    </div>
  </body>
</html>

beagle/ide/templates/ide/master_iframe.html
<!DOCTYPE html>
<html>
  <head>
    {% block mainhead %}
    <meta charset="utf-8"/> 
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}{{ idename }} &sdot; {{ request.get_host }}{% endblock %}</title>
    <link rel="shortcut icon" href="{{ STATIC_URL }}ide/img/favicon.ico" />
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700' rel='stylesheet' type='text/css'/>
    <link href='https://fonts.googleapis.com/css?family=Droid+Sans+Mono&v1' rel='stylesheet' type='text/css'/>
    <link href='https://fonts.googleapis.com/css?family=Gentium+Basic' rel='stylesheet' type='text/css'>
    
    <link href='{{ STATIC_URL }}ide/css/iframe.css' rel='stylesheet' type='text/css'>
    <link href='{{ STATIC_URL }}ide/css/kendo_styles/kendo.{{ request.user.preferences.uitheme }}.min.css' rel='stylesheet' type='text/css'/>
    
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/jquery.js'></script>
    <script type="text/javascript" src='{{ STATIC_URL }}ide/js/iframe.js'></script>
    
    {% endblock %}
    {% block head %}{% endblock %}
  </head>
  <body class="k-content">
    {% block content %}{% endblock %}
    {% block footer %}{% endblock %}
  </body>
</html>

beagle/ide/templates/ide/term_pref.html
{% extends "ide/master_iframe.html" %}
{% block head %}
<base target="_blank">
<style type="text/css">
  input[type="text"] {
    width: 400px;
  }
  
  input#id_tfontsize {
    width: 40px;
  }
</style>
{% endblock %}
{% block content %}
<form action="{% url ide-terminal-pref %}" method="post" class="pref_form" enctype="multipart/form-data" target="_self">
  {% csrf_token %}
  <table>
    <tr>
      <td>
        {% if form.errors.bg %}{{ form.errors.bg }}{% endif %}
        <strong>Background Image</strong>:<br>{{ form.bg }}
      </td>
    </tr>
    <tr>
      <td>
        {% if form.errors.tfontsize %}{{ form.errors.tfontsize }}{% endif %}
        <strong>Font Size</strong>:<br>{{ form.tfontsize }}
      </td>
    </tr>
    <tr>
      <td>
        {% if form.errors.font %}{{ form.errors.font }}{% endif %}
        <strong>Font</strong>:<br>{{ form.font }}
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <input type="submit" name="task" value="Kaydet"/>
      </td>
    </tr>
  </table>
</form>
{% endblock %}